/**
 * Emits the cross-language frame corpus.
 *
 * The C++ engine is the reference implementation of the PSNL wire format, so it
 * produces the vectors and the Python `psnl` package must reproduce them
 * byte-for-byte (encode) and interpret them identically (decode). Anchoring both
 * sides to a shared corpus is what stops the server and the console from drifting
 * into two subtly different protocols.
 *
 * Output: <outdir>/*.bin  — raw on-wire frames, exactly as NetLink emits them
 *         <outdir>/manifest.json — what each frame is supposed to decode to
 *
 * Regenerate with `make vectors`. The corpus is committed; a diff in it is a
 * deliberate protocol change and should be reviewed as one.
 */

#include <stdio.h>
#include <string.h>

#include "mocktransport.hh"
#include "netlink.hh"
#include "netprotocol.hh"
#include "networkmanager.hh"
#include "sio1.hh"

using namespace psxsplash;
using namespace psxsplash::net;
using psxsplash::test::MockTransport;
using psxsplash::test::RecordingHandler;

namespace {

char g_outDir[512] = ".";
FILE* g_manifest = nullptr;
bool g_first = true;

void writeBin(const char* name, const uint8_t* data, uint32_t len) {
    char path[640];
    snprintf(path, sizeof(path), "%s/%s.bin", g_outDir, name);
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", path);
        return;
    }
    fwrite(data, 1, len, f);
    fclose(f);
}

void appendManifest(const char* name, const char* type, uint8_t srcSlot, uint8_t flags, uint16_t seq,
                    const uint8_t* payload, uint16_t payloadLen) {
    if (!g_first) fprintf(g_manifest, ",\n");
    g_first = false;
    fprintf(g_manifest, "    {\n");
    fprintf(g_manifest, "      \"name\": \"%s\",\n", name);
    fprintf(g_manifest, "      \"type\": \"%s\",\n", type);
    fprintf(g_manifest, "      \"src_slot\": %u,\n", srcSlot);
    fprintf(g_manifest, "      \"flags\": %u,\n", flags);
    fprintf(g_manifest, "      \"seq\": %u,\n", seq);
    fprintf(g_manifest, "      \"payload\": \"");
    for (uint16_t i = 0; i < payloadLen; i++) fprintf(g_manifest, "%02x", payload[i]);
    fprintf(g_manifest, "\"\n    }");
}

// Emit one vector by driving the real NetLink and capturing what it puts on the
// wire — never by hand-assembling bytes, so the corpus can't drift from the
// implementation it is meant to pin down.
class Emitter {
  public:
    Emitter() : m_transport(m_out, m_in), m_link(m_transport, m_handler) {}

    void emit(const char* name, const char* typeName, PacketType type, uint8_t slot, const uint8_t* payload,
              uint16_t len, bool reliable = false) {
        emitImpl(name, typeName, type, slot, payload, len, reliable, 0);
    }

    // Unreliable send with an explicit header flags byte (c_flagRebind).
    void emitFlagged(const char* name, const char* typeName, PacketType type, uint8_t slot, const uint8_t* payload,
                     uint16_t len, uint8_t flags) {
        emitImpl(name, typeName, type, slot, payload, len, false, flags);
    }

  private:
    void emitImpl(const char* name, const char* typeName, PacketType type, uint8_t slot, const uint8_t* payload,
                  uint16_t len, bool reliable, uint8_t flags) {
        m_out.clear();
        m_link.reset();
        m_link.setLocalSlot(slot);

        if (reliable) {
            m_link.sendReliable(type, payload, len);
        } else {
            m_link.send(type, payload, len, flags);
        }

        uint8_t frame[1 + sizeof(PacketHeader) + c_maxPayload + 2];
        uint32_t n = 0;
        uint8_t b;
        while (m_out.pop(b) && n < sizeof(frame)) frame[n++] = b;

        // seq: unreliable uses m_txSeq starting at 1; reliable uses m_txEventSeq,
        // also starting at 1. Both are 1 here because reset() precedes each emit.
        writeBin(name, frame, n);
        appendManifest(name, typeName, slot, flags, 1, payload, len);
        printf("  %-24s %3u bytes\n", name, n);
    }

    MockTransport::Ring m_out, m_in;
    MockTransport m_transport;
    RecordingHandler m_handler;
    NetLink m_link;
};

}  // namespace

int main(int argc, char** argv) {
    if (argc > 1) snprintf(g_outDir, sizeof(g_outDir), "%s", argv[1]);

    char manifestPath[640];
    snprintf(manifestPath, sizeof(manifestPath), "%s/manifest.json", g_outDir);
    g_manifest = fopen(manifestPath, "wb");
    if (!g_manifest) {
        fprintf(stderr, "cannot write %s\n", manifestPath);
        return 1;
    }

    fprintf(g_manifest, "{\n");
    fprintf(g_manifest, "  \"_comment\": \"Generated by tests/host/gen_vectors.cpp — do not hand-edit. Regenerate with `make vectors`.\",\n");
    fprintf(g_manifest, "  \"proto_version\": %u,\n", c_protoVersion);
    fprintf(g_manifest, "  \"magic\": %u,\n", c_magic);
    fprintf(g_manifest, "  \"sync_byte\": %u,\n", c_syncByte);
    fprintf(g_manifest, "  \"max_payload\": %u,\n", c_maxPayload);

    // Every constant the SERVER also holds a copy of.
    //
    // Duplicated constants are not a tidiness problem here; they are the failure
    // mode with the worst debugging profile this project has met. The console and
    // the bridge once ran at different bauds because the number was written in two
    // places and only one was changed — and a baud mismatch is indistinguishable
    // from an unplugged cable. Emitting them makes the ENGINE the single source of
    // truth and turns any future drift into a failing assertion rather than a dead
    // link or, worse, a silently mis-decoded position.
    //
    // Read from the real constants, never retyped. A hand-copied literal here
    // would reproduce the exact bug this is meant to prevent, one layer further
    // out and harder to see.
    fprintf(g_manifest, "  \"max_slots\": %u,\n", (unsigned)psxsplash::NetworkManager::c_maxSlots);
    fprintf(g_manifest, "  \"legacy_record_size\": %u,\n", c_snapLegacyRecordSize);
    fprintf(g_manifest, "  \"snap_format_legacy\": %u,\n", (unsigned)c_snapFormatLegacy);
    fprintf(g_manifest, "  \"snap_format_compact\": %u,\n", (unsigned)c_snapFormatCompact);
    fprintf(g_manifest, "  \"compact_origin_bytes\": %u,\n", c_snapOriginBytes);
    fprintf(g_manifest, "  \"compact_avatar_size\": %u,\n", c_snapCompactAvatarSize);
    fprintf(g_manifest, "  \"compact_object_size\": %u,\n", c_snapCompactObjectSize);
    fprintf(g_manifest, "  \"compact_max_offset\": %u,\n", c_snapCompactMaxOffset);
    fprintf(g_manifest, "  \"compact_max_shift\": %u,\n", c_snapCompactMaxShift);
    fprintf(g_manifest, "  \"fp12_two_pi\": %d,\n", c_fp12TwoPi);
    fprintf(g_manifest, "  \"default_baud\": %u,\n", (unsigned)psxsplash::Sio1::c_defaultBaud);

    fprintf(g_manifest, "  \"vectors\": [\n");

    printf("generating vectors into %s\n", g_outDir);
    Emitter e;

    // Handshake.
    HelloPayload hello{};
    hello.magic = c_magic;
    hello.protoVersion = c_protoVersion;
    hello.reserved = 0;
    hello.sceneHash = 0xDEADBEEFu;
    hello.tiebreak = 0x12345678u;
    e.emit("hello", "Hello", PacketType::Hello, c_noSlot, (const uint8_t*)&hello, sizeof(hello));

    HelloAckPayload ack{};
    ack.magic = c_magic;
    ack.protoVersion = c_protoVersion;
    ack.yourSlot = 3;
    ack.hostSlot = c_hostSlot;
    ack.sceneHash = 0xDEADBEEFu;
    ack.playerCount = 7;
    e.emit("helloack", "HelloAck", PacketType::HelloAck, c_hostSlot, (const uint8_t*)&ack, sizeof(ack));

    // Zero-length frames (exercise the len==0 -> Crc path).
    e.emit("ping_empty", "Ping", PacketType::Ping, 1, nullptr, 0);
    e.emit("bye_empty", "Bye", PacketType::Bye, 2, nullptr, 0);

    // Ping/Pong carrying measurements. Pinned as vectors because these two are the
    // only frames whose CONTENT the two implementations both have to agree on for
    // pacing to work -- a silent layout drift here would leave each end confidently
    // pacing itself by a misread number, which is a worse failure than not pacing
    // at all.
    PingPayload ping{};
    ping.echo = 0xC0FFEEu;
    ping.goodput = 5400;
    ping.rttMillis = 93;
    e.emit("ping_measured", "Ping", PacketType::Ping, 1, (const uint8_t*)&ping, sizeof(ping));

    PingPayload pong{};
    pong.echo = 0xC0FFEEu;
    pong.goodput = 11520;
    pong.rttMillis = 4;
    e.emit("pong_measured", "Pong", PacketType::Pong, c_hostSlot, (const uint8_t*)&pong, sizeof(pong));

    // A realistic 10-avatar snapshot: [u8 avatarCount][u8 objectCount][u16 rsv]
    // + 20-byte records. This is the packet the star server fans out, so its size
    // is the number the bandwidth budget lives or dies by.
    {
        uint8_t snap[4 + 10 * 20];
        memset(snap, 0, sizeof(snap));
        snap[0] = 10;  // avatarCount
        snap[1] = 0;   // objectCount
        for (int i = 0; i < 10; i++) {
            uint8_t* r = snap + 4 + i * 20;
            r[0] = (uint8_t)i;  // slot
            r[1] = 0x01;        // SNAP_FLAG_ACTIVE
            int32_t px = (i + 1) * 4096, py = -(i + 1) * 2048, pz = (i + 1) * 1024;
            int32_t yaw = i * 400;
            memcpy(r + 4, &px, 4);
            memcpy(r + 8, &py, 4);
            memcpy(r + 12, &pz, 4);
            memcpy(r + 16, &yaw, 4);
        }
        e.emit("snapshot_10_avatars", "Snapshot", PacketType::Snapshot, c_hostSlot, snap, sizeof(snap));
    }

    // Boundary: the largest frame the protocol permits.
    {
        uint8_t big[c_maxPayload];
        for (int i = 0; i < c_maxPayload; i++) big[i] = (uint8_t)(i * 31 + 7);
        e.emit("snapshot_max_payload", "Snapshot", PacketType::Snapshot, c_hostSlot, big, c_maxPayload);
    }

    // The COMPACT ten-avatar snapshot: the same information as
    // snapshot_10_avatars, in 116 payload bytes instead of 204.
    //
    // Pinned as a vector because the console and the server quantise these numbers
    // independently, on opposite sides of the wire, and a disagreement would not
    // fail loudly -- it would place every remote player slightly wrong, which
    // reads as a physics bug. This is the corpus entry that makes that a test
    // failure instead.
    {
        const int32_t originX = 4096, originY = -20480, originZ = 1024;
        const uint32_t shift = 6;
        uint8_t snap[4 + c_snapOriginBytes + c_snapCompactAvatarSize * 10];
        snap[0] = 10;                    // avatarCount
        snap[1] = 0;                     // objectCount
        snap[2] = c_snapFormatCompact;   // format
        snap[3] = (uint8_t)shift;        // posShift
        uint32_t o = 4;
        __builtin_memcpy(snap + o + 0, &originX, 4);
        __builtin_memcpy(snap + o + 4, &originY, 4);
        __builtin_memcpy(snap + o + 8, &originZ, 4);
        o += c_snapOriginBytes;
        for (uint32_t i = 1; i <= 10; i++) {
            const int32_t px = (int32_t)i * 4096;
            const int32_t py = -(int32_t)i * 2048;
            const int32_t pz = (int32_t)i * 1024;
            const int32_t yaw = (int32_t)i * 400;
            snap[o + 0] = (uint8_t)i;    // slot
            snap[o + 1] = 0x01;          // SNAP_FLAG_ACTIVE
            uint16_t dx = encodeCompactOffset(px, originX, shift);
            uint16_t dy = encodeCompactOffset(py, originY, shift);
            uint16_t dz = encodeCompactOffset(pz, originZ, shift);
            uint16_t ry = (uint16_t)normalizeFp12Angle(yaw);
            __builtin_memcpy(snap + o + 2, &dx, 2);
            __builtin_memcpy(snap + o + 4, &dy, 2);
            __builtin_memcpy(snap + o + 6, &dz, 2);
            __builtin_memcpy(snap + o + 8, &ry, 2);
            o += c_snapCompactAvatarSize;
        }
        e.emit("snapshot_10_compact", "Snapshot", PacketType::Snapshot, c_hostSlot, snap, (uint16_t)o);
    }

    // Reliable channel.
    {
        uint8_t ev[8];
        int32_t id = 1234, arg = -99;
        memcpy(ev + 0, &id, 4);
        memcpy(ev + 4, &arg, 4);
        e.emit("event_game", "Event", PacketType::Event, 1, ev, sizeof(ev), /*reliable=*/true);
    }
    e.emit("eventack", "EventAck", PacketType::EventAck, c_hostSlot, nullptr, 0);
    {
        // [actorId:u16][serialized self.sync]
        uint8_t obj[2 + 6];
        uint16_t actorId = 42;
        memcpy(obj, &actorId, 2);
        memcpy(obj + 2, "\x01\x02\x03\x04\x05\x06", 6);
        e.emit("objectstate", "ObjectState", PacketType::ObjectState, c_hostSlot, obj, sizeof(obj),
               /*reliable=*/true);
    }

    // AppData: the game's opaque channel. The payload here is a plausible room
    // list — [subtype][page][pageCount][count] + 16-byte room records — which is
    // also the shape the 244B <= 256B "one packet per lobby refresh" claim rests
    // on.
    {
        uint8_t rooms[4 + 3 * 16];
        memset(rooms, 0, sizeof(rooms));
        rooms[0] = 1;  // subtype: RoomListReply
        rooms[1] = 0;  // page
        rooms[2] = 1;  // pageCount
        rooms[3] = 3;  // count
        const char* names[3] = {"SKELD", "MIRA", "POLUS"};
        for (int i = 0; i < 3; i++) {
            uint8_t* r = rooms + 4 + i * 16;
            uint16_t roomId = (uint16_t)(100 + i);
            memcpy(r, &roomId, 2);
            r[2] = (uint8_t)(i + 2);  // playerCount
            r[3] = (uint8_t)(i == 2 ? 0x01 : 0x00);  // flags: private
            memcpy(r + 4, names[i], strlen(names[i]));  // char name[12], NUL-padded
        }
        e.emit("appdata_roomlist", "AppData", PacketType::AppData, 1, rooms, sizeof(rooms),
               /*reliable=*/true);
    }

    // A Hello carrying c_flagRebind — the "keep my slot across a scene change"
    // handshake. This is the only vector with a non-zero header flags byte.
    {
        HelloPayload rebind{};
        rebind.magic = c_magic;
        rebind.protoVersion = c_protoVersion;
        rebind.sceneHash = 0xC0FFEE01u;
        rebind.tiebreak = 0x12345678u;
        e.emitFlagged("hello_rebind", "Hello", PacketType::Hello, 3, (const uint8_t*)&rebind, sizeof(rebind),
                      c_flagRebind);
    }

    fprintf(g_manifest, "\n  ]\n}\n");
    fclose(g_manifest);
    printf("wrote manifest.json\n");
    return 0;
}
