name: Build

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  engine:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: ghcr.io/grumpycoders/pcsx-redux-build:latest
    strategy:
      fail-fast: false
      matrix:
        loader: [ pcdrv, cdrom ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          set-safe-directory: true
      - name: Build
        run: make -j4 all LOADER=${{ matrix.loader }}
      - name: Build the smallest engine
        run: make -j4 all LOADER=${{ matrix.loader }} FEATURES=none

  host-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Host tests
        run: make -C tests/host
